### ISSUE TITLE
[IOS] XCode 14.3: rsync error: some files could not be transferred

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/nativescript-ui-charts#48]
Hello everyone, with the ns 8.5 version I am no longer able to debug my app on my IOS emulator. I separated this bug into a dedicated project public to debug it here https://github.com/vicmasa/ns853

### Which platform(s) does your issue occur on?
- iOS
- iOS 16.4 
- emulator

```yaml
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 19.8.1
npm: 9.5.1
nativescript: 8.5.3

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.1
python: 2.7.18
python3: 3.9.6
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.5.0",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/ui-charts": "^0.2.4"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/webpack": "~5.0.14"
}
```

**NS DOCTOR**
No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 14.3.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.5.3 version and is up to date.
✔ Component @nativescript/core has 8.5.1 version and is up to date.
✔ Component @nativescript/ios has 8.5.1 version and is up to date.
✔ Component @nativescript/android has 8.5.0 version and is up to date.

**ERROR DETAILS:**

Searching for devices...
Preparing project...
webpack is watching the files...
assets by status 87.4 KiB [compared for emit]
  asset runtime.js 86.2 KiB [emitted] [compared for emit] (name: runtime)
  asset tns_modules/inspector_modules.js 1.22 KiB [compared for emit] (name: tns_modules/inspector_modules)
asset vendor.js 7.27 MiB [emitted] (name: vendor) (id hint: defaultVendor)
asset bundle.js 357 KiB [emitted] (name: bundle)
Entrypoint bundle 7.7 MiB = runtime.js 86.2 KiB vendor.js 7.27 MiB bundle.js 357 KiB
Entrypoint tns_modules/inspector_modules 7.35 MiB = runtime.js 86.2 KiB vendor.js 7.27 MiB tns_modules/inspector_modules.js 1.22 KiB
runtime modules 24.8 KiB 11 modules
orphan modules 302 bytes [orphan] 5 modules
modules by path ./node_modules/@nativescript/ 1.76 MiB 301 modules
modules by path ./node_modules/css-tree/ 317 KiB 113 modules
modules by path ./app/ 128 KiB 13 modules
modules by path ./node_modules/source-map/lib/*.js 36.3 KiB 6 modules
modules by path ./node_modules/reduce-css-calc/dist/ 131 KiB 5 modules
modules by path ./node_modules/postcss-value-parser/lib/*.js 12.5 KiB
  ./node_modules/postcss-value-parser/lib/index.js 607 bytes [built] [code generated]
  + 4 modules
modules by path ./node_modules/mdn-data/css/*.json 242 KiB
  ./node_modules/mdn-data/css/at-rules.json 11.6 KiB [built] [code generated]
  + 2 modules
+ 5 modules
webpack 5.79.0 compiled successfully in 1602 ms
Webpack compilation complete. Watching for file changes.
File change detected. Starting incremental webpack compilation...
Updating runtime package.json with configuration values...
Project successfully prepared (ios)
Building project...
Xcode build...
assets by status 7.7 MiB [cached] 4 assets
Entrypoint bundle 7.7 MiB = runtime.js 86.2 KiB vendor.js 7.27 MiB bundle.js 357 KiB
Entrypoint tns_modules/inspector_modules 7.35 MiB = runtime.js 86.2 KiB vendor.js 7.27 MiB tns_modules/inspector_modules.js 1.22 KiB
cached modules 2.84 MiB (javascript) 24.8 KiB (runtime) [cached] 464 modules
javascript modules 1.8 KiB
  ./app/ sync .(xml%7Cjs%7Cs?css)$ 528 bytes [built]
  ./app/components/charts/charts.xml 799 bytes [optional] [built]
  ./app/components/google-maps/google-maps.xml 518 bytes [optional] [built]
webpack 5.79.0 compiled successfully in 68 ms
Webpack compilation complete. Watching for file changes.
2023-04-19 09:55:55.507 xcodebuild[26717:566592] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
./.build_env_vars.sh: line 508: declare: UID: readonly variable
NSLD: Swift bridging header '*-Swift.h' not found under '/Users/victor/Library/Developer/Xcode/DerivedData/ns853-accewalgpdkijncvnqbrrhqwtmdn/Build/Intermediates.noindex/ns853.build/Debug-iphonesimulator/ns853.build/Objects-normal/arm64'
Generating metadata...~/invian/ns/ns853/platforms/ios/internal/metadata-generator-arm64/bin ~/invian/ns/ns853/platforms/ios
Python version: 3.9.6 (default, Mar 10 2023, 20:16:38) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
Generating metadata for arm64
Metadata Generator Arguments: 
./objc-metadata-generator -verbose -output-bin /Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/metadata-arm64.bin -output-umbrella /Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/umbrella-arm64.h -docset-path /Users/victor/Library/Developer/Shared/Documentation/DocSets/com.apple.adc.documentation.iOS.docset Xclang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk -std=gnu99 -target arm64-apple-ios16.4-simulator -I/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/include -I/Users/victor/invian/ns/ns853/platforms/ios/internal/Swift-Modules -I/Users/victor/invian/ns/ns853/platforms/ios/internal -I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/ui-charts/platforms/ios/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/ns853/platforms/ios/internal/ -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Maps/Frameworks -F/Users/victor/invian/ns/ns853/platforms/ios/Pods/Highcharts/development -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Base -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Maps -F/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios -DCOCOAPODS=1 -DDEBUG=1 
Clang Arguments: 
"-v", "-x", "objective-c", "-fno-objc-arc", "-fmodule-maps", "-ferror-limit=0", "-Wno-unknown-pragmas", "-Wno-ignored-attributes", "-Wno-nullability-completeness", "-Wno-expansion-to-defined", "-D__NATIVESCRIPT_METADATA_GENERATOR=1", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk", "-std=gnu99", "-target", "arm64-apple-ios16.4-simulator", "-I/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/include", "-I/Users/victor/invian/ns/ns853/platforms/ios/internal/Swift-Modules", "-I/Users/victor/invian/ns/ns853/platforms/ios/internal", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/ui-charts/platforms/ios/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/ns853/platforms/ios/internal/", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Base/Frameworks", "-F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Maps/Frameworks", "-F/Users/victor/invian/ns/ns853/platforms/ios/Pods/Highcharts/development", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Base", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Maps", "-F/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios", "-DCOCOAPODS=1", "-DDEBUG=1", 
Merged 1097 categories.
Result: 55963 declarations from 176 top level modules
Done! Running time: 4.1969 sec 
Saving metadata generation's stderr stream to: /Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-arm64.txt
Generating metadata for x86_64
Metadata Generator Arguments: 
./objc-metadata-generator -verbose -output-bin /Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/metadata-x86_64.bin -output-umbrella /Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/umbrella-x86_64.h -docset-path /Users/victor/Library/Developer/Shared/Documentation/DocSets/com.apple.adc.documentation.iOS.docset Xclang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk -std=gnu99 -target x86_64-apple-ios16.4-simulator -I/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/include -I/Users/victor/invian/ns/ns853/platforms/ios/internal/Swift-Modules -I/Users/victor/invian/ns/ns853/platforms/ios/internal -I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/ui-charts/platforms/ios/src -I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/ns853/platforms/ios/internal/ -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Maps/Frameworks -F/Users/victor/invian/ns/ns853/platforms/ios/Pods/Highcharts/development -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Base -F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Maps -F/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios -DCOCOAPODS=1 -DDEBUG=1 
Clang Arguments: 
"-v", "-x", "objective-c", "-fno-objc-arc", "-fmodule-maps", "-ferror-limit=0", "-Wno-unknown-pragmas", "-Wno-ignored-attributes", "-Wno-nullability-completeness", "-Wno-expansion-to-defined", "-D__NATIVESCRIPT_METADATA_GENERATOR=1", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk", "-std=gnu99", "-target", "x86_64-apple-ios16.4-simulator", "-I/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/include", "-I/Users/victor/invian/ns/ns853/platforms/ios/internal/Swift-Modules", "-I/Users/victor/invian/ns/ns853/platforms/ios/internal", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/ui-charts/platforms/ios/src", "-I/Users/victor/invian/ns/ns853/platforms/ios/../../App_Resources/iOS/src", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/ns853/platforms/ios/internal/", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Base/Frameworks", "-F/Users/victor/invian/ns/ns853/platforms/ios/Pods/GoogleMaps/Maps/Frameworks", "-F/Users/victor/invian/ns/ns853/platforms/ios/Pods/Highcharts/development", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Base", "-F/Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleMaps/Maps", "-F/Users/victor/invian/ns/ns853/platforms/ios/../../node_modules/@nativescript/core/platforms/ios", "-DCOCOAPODS=1", "-DDEBUG=1", 
Merged 1097 categories.
Result: 56019 declarations from 177 top level modules
Done! Running time: 3.9593 sec 
Saving metadata generation's stderr stream to: /Users/victor/invian/ns/ns853/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-x86_64.txt
~/invian/ns/ns853/platforms/ios
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/victor/invian/ns/ns853/platforms/ios/Pods/Highcharts/development/Highcharts.framework/Highcharts' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using codesigning identity override: 
note: Building targets in dependency order
note: Run script build phase 'NativeScript PreBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ns853' from project 'ns853')
note: Run script build phase 'NativeScript PreLink' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ns853' from project 'ns853')
note: Run script build phase 'NativeScript PostBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ns853' from project 'ns853')
** BUILD FAILED **

Unable to apply changes on device: BAE26DD3-AAD3-4BAD-82DD-E64231EFC609. Error is: Command xcodebuild failed with exit code 65.

**Comment by NathanWalker** [comment]
Hi @vicmasa it appears the package shared is not complete as the stack shows the issue being an older version of google maps plugin in use:
@nativescript/google-maps

When possible to share full package in use so we can confirm versions in use. The output indicates a google maps arm64 issue in addition to other m1 expected cases when lower than needed versions are used of those plugins.

**Comment by NathanWalker** [comment]
See here: https://github.com/NativeScript/plugins/issues/483#issuecomment-1532352412

In future, if don't get a response within 72 hours, feel free to send email to any partner: https://nativescript.org/partners

**Comment by NathanWalker** [comment]
Regarding the title of this issue `rsync error` - that was a widely reported iOS ecosystem cocoapods issue [here](https://github.com/CocoaPods/CocoaPods/issues/11808). If you encounter that, just make sure you updated cocoapods on your system:

1. `which pod` to confirm where your cocoapods are installed.

A. If found to be in directory starting with `/usr/local`, likely `sudo gem install cocoapods`

B. If found to be in directory starting with `/usr/homebrew`, then `brew install cocoapods`

2. Confirm with `pod --version` that you have latest `1.12.1` or higher.

3. Clean project and run again.

**Comment by NathanWalker** [comment]
Closing this in favor of https://github.com/NativeScript/plugins/issues/483 - can continue confirmation there.
